name: First Action - Single
on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value:
        type: string
        description: Cualquier valor
        default: ""
        required: false  